/// Flutter icons JobFus
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  JobFus
///      fonts:
///       - asset: fonts/JobFus.ttf
///
/// 
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
///
import 'package:flutter/widgets.dart';

class JobFus {
  JobFus._();

  static const _kFontFam = 'JobFus';
  static const String? _kFontPkg = null;

  static const IconData exchange = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download = IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload = IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sign_out = IconData(0xf339, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
